@extends('admin.layout')

@section('title', $insight->exists ? 'Edit insight' : 'Write an insight')
@section('crumb', 'INSIGHTS / '.strtoupper($insight->exists ? 'EDIT STORY' : 'NEW STORY'))

@section('content')
<form class="editor-form" method="post" enctype="multipart/form-data" action="{{ $insight->exists ? route('admin.insights.update', $insight) : route('admin.insights.store') }}">
  @csrf @if ($insight->exists) @method('PUT') @endif
  <div class="editor-top"><a class="editor-back" href="{{ route('admin.insights.index') }}">← <span>All insights</span></a><div class="editor-actions"><span class="editor-save-state">{{ $insight->exists ? 'Last saved '.$insight->updated_at->diffForHumans() : 'A new story' }}</span><button class="studio-button studio-button-outline" type="submit" name="is_published" value="0">Save draft</button><button class="studio-button studio-button-dark" type="submit" name="is_published" value="1">{{ $insight->is_published ? 'Update story' : 'Publish story' }} <span>↗</span></button></div></div>
  <div class="editor-grid"><div class="editor-main">
    <label class="editor-label" for="title">STORY TITLE</label><input class="editor-title-input" id="title" name="title" value="{{ old('title', $insight->title) }}" placeholder="Give your story a clear, considered title" required maxlength="255">@error('title')<span class="field-error">{{ $message }}</span>@enderror
    <div class="editor-field"><label class="editor-label" for="excerpt">INTRODUCTION <span>SHOWN ON YOUR HOMEPAGE</span></label><textarea id="excerpt" name="excerpt" rows="3" maxlength="320" placeholder="In a sentence or two, what should readers take away?" required>{{ old('excerpt', $insight->excerpt) }}</textarea><div class="field-bottom"><span>A short introduction to draw readers in.</span><span id="excerpt-count">0 / 320</span></div>@error('excerpt')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="editor-field"><label class="editor-label">THE STORY <span>YOUR POINT OF VIEW, IN FULL</span></label><div class="rich-toolbar" role="toolbar" aria-label="Text formatting"><button type="button" data-command="formatBlock" data-value="p" title="Paragraph">¶</button><i></i><button type="button" data-command="bold" title="Bold"><b>B</b></button><button type="button" data-command="italic" title="Italic"><em>I</em></button><button type="button" data-command="formatBlock" data-value="h2" title="Heading">H₂</button><button type="button" data-command="formatBlock" data-value="h3" title="Subheading">H₃</button><i></i><button type="button" data-command="insertUnorderedList" title="Bullet list">☷</button><button type="button" data-command="insertOrderedList" title="Numbered list">1.</button><button type="button" data-command="createLink" title="Add link">↗</button><i></i><button type="button" data-command="removeFormat" title="Clear formatting">Tx</button></div>@php($editorBody = \App\Support\RichText::clean(old('body', $insight->body ?? '')))<div class="rich-editor" contenteditable="true" role="textbox" aria-label="Insight body" aria-multiline="true" data-placeholder="Start writing. Share an observation, explain the context and leave readers with a clear perspective.">{!! $editorBody !!}</div><textarea class="rich-source" name="body" hidden>{{ $editorBody }}</textarea>@error('body')<span class="field-error">{{ $message }}</span>@enderror</div>
  </div><aside class="editor-side"><section class="editor-side-card"><h3>Story details</h3><div class="editor-field"><label class="editor-label" for="category">CATEGORY</label><input id="category" name="category" value="{{ old('category', $insight->category ?: 'Market perspectives') }}" placeholder="Market perspectives" maxlength="80" required>@error('category')<span class="field-error">{{ $message }}</span>@enderror</div><div class="editor-field"><label class="editor-label" for="published_at">PUBLICATION DATE</label><input id="published_at" type="datetime-local" name="published_at" value="{{ old('published_at', $insight->published_at?->format('Y-m-d\TH:i')) }}"><small>Future dates keep an article off the public site until then.</small>@error('published_at')<span class="field-error">{{ $message }}</span>@enderror</div></section>
    <section class="editor-side-card"><h3>Cover image</h3><p class="side-hint">A considered image gives your story a strong first impression.</p>@if ($insight->cover_image)<img class="cover-preview" src="{{ asset('storage/'.$insight->cover_image) }}" alt="Current cover image">@endif<label class="upload-control" for="cover_image"><span>＋</span><b>Choose an image</b><small>JPG, PNG or WebP · up to 5 MB</small><input id="cover_image" type="file" name="cover_image" accept="image/*"></label>@error('cover_image')<span class="field-error">{{ $message }}</span>@enderror</section>
    <div class="editor-tip"><span>✳</span><p><b>A little room to think.</b><br>Use short paragraphs and clear subheadings to make your ideas easy to follow.</p></div>
  </aside></div>
</form>
@endsection

@push('scripts')<script src="{{ asset('admin-editor.js') }}" defer></script>@endpush
